name: Generate github apps token
on:
  workflow_call:
    inputs:
      apps_id:
        required: true
        type: string
    secrets:
      apps_private_key:
        required: true
    outputs:
      github_apps_install_token:
        description: "Returning a usable install token that can be used to authenticate to the Github API"
        value: ${{ jobs.token.token-output }}

jobs:
  token:
    name: generate install token
    runs-on: ubuntu-latesttoken
    outputs:
      token-output: ${{ steps.token-job.outputs.appsInstallToken }}
    steps:
      - uses: actions/checkout@v3
      
      - name: check files
        run: ls
      
      - name: Get token
        id: token-job
        env:
          apps_id: ${{ inputs.apps_id }}
          private_key: ${{ secrets.apps_private_key }}
        run: | 
          appsAccessToken=$(ruby token.arb "$private_key" "$apps_id")
          #echo "$appsAccessToken"

          appsInstallToken=$(curl -s -X POST \
            -H "Authorization: Bearer $appsToken" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/app/installations/25232808/access_tokens | jq .token)

          #echo "$appsInstallToken"
          # Trim quotes from the token
          installToken=$(echo "${installToken:1:${#installToken}-2}")
          
          # Return
          echo "::set-output name=appsInstallToken::$installToken"
          #echo "app_token=$appsInstallToken" >> $GITHUB_ENV
